scores = list(map(float, input("Enter 8 scores out of 10:").split()))
lowest = min(scores)
highest = max(scores)
total = sum(scores) - (lowest + highest)
average = total / (len(scores) - 2)
print("lowest score",lowest)
print("maximum score ",highest)
print("total point ",total)
print("average point ",average)
